### PR TITLE
Some sanitizing against SQL injections and some minor js fix closes(#45, #46)

### PR DESCRIPTION
**Pull request by PaulSchiretz**
First, sorry i didn't mean to combine those commits into one pull request, but well here I'am.

***Guard agains SQL injections as mentioned in #46***
I tried to fix some sanitizing issues(check the changed lines) and avoid to expose which users exist and which not.
Not sure if i found all the causes for the Vulnerability report as mentioned in #46 cause i don't have access to the full report as i'm not the owner of this plugin ;-). But i tried to find what i could! :-)

***Allow users to change the tag type of the tinvwl_add_to_wishlist_button as mentioned in #45***

This pull request removes the "a" tag from the a.tinvwl_add_to_wishlist_button selector in public.js on 4 occasions.
I use it like this on my site since a couple of months, cause it enables users to filter the wishlist button via the provided filer and change the html element from an "a" tag to a "button" for example.

Here a quick example how i use it:

```
add_filter('tinvwl_wishlist_button', 'custom_tinvwl_wishlist_button', 10, 7);
function custom_tinvwl_wishlist_button($content, $wishlist, $product, $is_loop, $icon, $action, $text) {
    if(empty($content)) {
        return $content;
    }

    $update_content = new WP_HTML_Tag_Processor( $content );
    if ( $update_content->next_tag( array( 'tag_name' => 'a', 'class_name' => 'tinvwl_add_to_wishlist_button' ) ) ) {
        $update_content->remove_attribute( 'name' );
        //if we replace the <a> tag with a <button> remove the role and add the type
        $update_content->remove_attribute( 'role' ); //remove the role
        $update_content->set_attribute( 'type', 'button' );
    }
    $content = $update_content->get_updated_html();

    //replace the a tag with a button tag, needs a custom override of public.js
    $replacement = '<button$1</button>';
    $content = preg_replace('/<a(.*)<\/a>/', $replacement, $content);
    return $content;
}
```

### CODE REVIEW

**Comment by PaulSchiretz** [comment]
@doozy can you have a look if this fixes the reported vulnerabilities?

**Comment by christopher-bio** [comment]
@auerserg Sorry for bothering you. Is there perhaps a chance you could have a look at this?

**Comment by PaulSchiretz** [comment]
Hi @christopher-bio i'm sorry to say this but i tried submitting a pull request, email them, reach the devs on github... no response. I meanwhile developed my own solution suitable for my very limited use case. In short i moved on, but i leave this pull request open for now, in case there is some activity in the future.

Cheers, Paul

**Comment by christopher-bio** [comment]
Hi @PaulSchiretz,
It is a shame, but we cannot help it. Thanks a lot for your efforts to fix this. 

Just out of curiousity: Did you develop a new solution for yourself or just used this plugin as a base?

**Comment by PaulSchiretz** [comment]
Hi @christopher-bio,

I first started of looking at using this plugin as a base, but i quickly realized that the source is really messy(specially the sql part), the functionality way to much for my needs and then started from scratch.

My solution is very basic, just adding/removing stuff to/from a single wishlist for logged in or not logged in users, sharing can be enabled if needed. That's it. Some ajax calls, 2 db tables, 1 cron job for deleting outdated wishlists... not much to it. Styling is just what i used in my theme anyway.

I would be happy to share it with you, I use it in production on my girlfriends shop and for that it's just perfect, lightweight, safe and does it's job, BUT it's not "public plugin ready" as it's relying on some functionality of a custom Theme i developed... if you really want me to, and maybe join me, we could adapt the solution and make something out of it... but that would need a little afford. you know, the last 20% of making a solution a product ;-)

But what could help you for now: While developing i took some inspiration from wcboost-wishlist which i found lightweight and clean coded, maybe that would be a good solution for you...?

Cheers,
Paul

**Comment by christopher-bio** [comment]
Hi @PaulSchiretz,

This sounds way more sophisticated than I am. I tried to find all possible SQL injection points and make them safe (without being able to tell whether that was necessary for all of them). I have also made quite some adjustments to the plugin recently to make it compliant with the upcoming accessibility guidelines.

Nevertheless, staying with this plugin is also not my favorite decision. I will definitely check wcboost-wishlist. Did you also migrate existing wishlists to your new plugin?

**Comment by PaulSchiretz** [comment]
Hi @christopher-bio 

I see, no i didn't migrate anything just a clean restart. We have a small store so I didn't worry about these couple of lists.

Cheers,
Paul

**Review by doozy — APPROVED** [review]

**Pull request merged**
